### post paper
POST http://localhost:8080/model/paper
Content-Type: application/json

{
    "Judul": "Pengaruh Urbanisasi Terhadap Lingkungan Perkotaan",
    "Penulis": "Ahmad Fauzan",
    "Tahun": 2023,
    "Abstrak": "Artikel ini meneliti dampak urbanisasi terhadap kualitas lingkungan di kota-kota besar, dengan fokus pada polusi udara dan pengelolaan limbah...",
    "Source": "Jurnal Studi Perkotaan"
}

